[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solever_leverage = "8En47DwXiCWdsiDsRZwuEr2W2wSexFhf4mF9eLiiijoH"
solever = "GWukmhTitefhHyGpz3G8a6e5RbGGWaiEJgCdRWpMfXYj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
